# Generated by Django 6.0.6 on 2026-07-01 14:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('turma', models.CharField(max_length=50, verbose_name='Turma')),
                ('tipo_usuario', models.CharField(choices=[('ALUNO', 'Aluno'), ('ADMIN', 'Administrador')], default='ALUNO', max_length=10, verbose_name='Tipo de Usuário')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set_custom', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_permissions_set_custom', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refeicao', models.CharField(max_length=200, verbose_name='Refeição')),
                ('avaliacao_geral', models.IntegerField(verbose_name='Avaliação Geral')),
                ('sabor', models.IntegerField(verbose_name='Sabor')),
                ('apresentacao', models.IntegerField(verbose_name='Apresentação')),
                ('temperatura', models.IntegerField(verbose_name='Temperatura')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
    ]
